# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "ohci_pci" "ehci_pci" "ahci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-8e0d0237-f4ec-4064-ab57-a3a8505ab7f4";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-8e0d0237-f4ec-4064-ab57-a3a8505ab7f4".device = "/dev/disk/by-uuid/8e0d0237-f4ec-4064-ab57-a3a8505ab7f4";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8A60-5778";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  virtualisation.virtualbox.guest.enable = true;
}
